site_name: "Minimal Information About a new Cell Type"
theme: readthedocs
docs_dir: target/docs
site_dir: docs
nav:
  - Index: index.md
  - Credits: credits.md
site_url: https://cmungall.github.io/mianct/
repo_url: https://github.com/cmungall/mianct/
